### ISSUE TITLE
Task: Shivanshu Bhaiya's Component

### ISSUE THREAD

**Issue by Satyajeet-Das** [Satyajeet-Das/SIH-Beta-Prototype#1]
Design
![image](https://github.com/user-attachments/assets/41ee0357-644f-4c41-8952-d1dab76c15dd)

Text for component
 Adaptive Learning Pathways:
Personalized Learning: Develop adaptive learning pathways based on the job seeker's progress and feedback.
Content Variety: Offer a mix of micro-courses, webinars, and hands-on projects relevant to the job market to enhance learning and skill development.

**Comment by ShivanshuKGupta** [comment]
Check out this [Commit](https://github.com/Satyajeet-Das/SIH-Beta-Prototype/commit/27d0cbc8e5a3bec91e719763e6d3be2007562c5a)

**Comment by ShivanshuKGupta** [comment]
Completed with [commit](https://github.com/Satyajeet-Das/SIH-Beta-Prototype/commit/ab35c32927137324fb9f2df387b1600c775f7b21)
